platform :ios, '13.0'
target 'Twenty' do
end

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
pod 'FirebaseUI'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'FBSDKCoreKit', '5.8.0'
pod 'FBSDKLoginKit', '5.8.0'
pod 'Firebase/Core', '6.1.0'
pod 'Firebase/DynamicLinks', '6.1.0'
