platform :ios, '13.0'

target 'Twenty' do
    pod 'CalendarKit', :git => 'https://github.com/yvetterowe/CalendarKit.git', :branch => '20'
    pod 'Firebase/Auth'
    pod 'FirebaseFirestoreSwift', :modular_headers => true
    pod 'FirebaseFirestore', :modular_headers => true
    pod 'GoogleSignIn'
    pod 'FBSDKCoreKit', '5.8.0'
    pod 'FBSDKLoginKit', '5.8.0'

    target 'TwentyTests' do
        inherit! :search_paths
    end
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end