platform :ios, '13.0'
target 'Twenty' do
end

pod 'Firebase/Auth'
pod 'FirebaseFirestoreSwift', :modular_headers => true
pod 'FirebaseFirestore', :modular_headers => true
pod 'GoogleSignIn'
pod 'FBSDKCoreKit', '5.8.0'
pod 'FBSDKLoginKit', '5.8.0'
